# Generated by Django 2.2.13 on 2021-02-25 11:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_secs',
            name='business_seconds',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
